name: Deploy to S3

on:
  push:
    branches:
      - main  # Change if you're using a different branch (like 'master')

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check AWS CLI version
        run: aws --version

      - name: Show files to be deployed
        run: ls -la

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
        run: |
          echo "Deploying files to S3 bucket: test-website-cicd-pipeline"
          aws s3 sync . s3://test-website-cicd-pipeline --delete
